### ISSUE TITLE
Does jsPsych Builder support React?

### ISSUE THREAD

**Issue by fenglier** [bjoluc/jspsych-builder#48] opened 2023-05-31 07:32 UTC
Hello, does jsPsych Builder support React? I haven't seen any examples indicating that React can be used.

**Comment by bjoluc** [comment] 2023-05-31 09:15
Hi @fenglier,
jsPsych Builder does support React/JSX – just rename the relevant source file(s) to `.jsx`/`.tsx` and you should be good to go. I'm aware of the lack of examples (#20), so I'm closing this as a duplicate of #20.
Cheers!

**Closed as not planned by bjoluc** 2023-05-31 09:15 UTC
Labels: documentation, duplicate

**Comment by fenglier** [comment] 2023-06-03 01:31
thanks
